baseURL = "https://example.com"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Madelyn Kapfhammer"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

[params]
title = "Madelyn Kapfhammer"
author = "Madelyn Kapfhammer"
description = "Student. Scientist. Software Engineer."
profilePicture = "images/profile.jpg"
keywords = ""
favicon = "favicons/"
customCss = ["css/custom.css"]
customJs = []
mainSections = ["post"]
images = ["images/site-feature-image.png"]
# Google Site Verification
#googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
[[params.socialIcons]]
icon = "fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/mkapfhammer"

[[params.socialIcons]]
icon = "fa-github"
title = "GitHub"
url = "https://github.com/MaddyKapfhammer"

[[params.socialIcons]]
icon = "fa-instagram"
title = "instagram"
url = "https://www.instagram.com/maddy.kapfhammer/?hl=en"

[[params.socialIcons]]
icon = "fa-envelope"
title = "e-mail"
url = "mailto:maddy.kapfhammer@gmail.com"

## Menu items

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 1
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 2
  identifier = "posts"
  url = "/post/"

  [[menu.main]]
  name = "Favorites"
  weight = 3
  identifier = "favorites"
  url = "/favorites/"

  [[menu.main]]
  name = "Research"
  weight = 4
  identifier = "research"
  url = "/research/"

  [[menu.main]]
  name = "About"
  weight = 5
  identifier = "about"
  url = "/about/"
